/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface CiaSearch {
    }
    interface CiaSearchInput {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCiaSearchElement extends Components.CiaSearch, HTMLStencilElement {
    }
    var HTMLCiaSearchElement: {
        prototype: HTMLCiaSearchElement;
        new (): HTMLCiaSearchElement;
    };
    interface HTMLCiaSearchInputElement extends Components.CiaSearchInput, HTMLStencilElement {
    }
    var HTMLCiaSearchInputElement: {
        prototype: HTMLCiaSearchInputElement;
        new (): HTMLCiaSearchInputElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "cia-search": HTMLCiaSearchElement;
        "cia-search-input": HTMLCiaSearchInputElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CiaSearch {
    }
    interface CiaSearchInput {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "cia-search": CiaSearch;
        "cia-search-input": CiaSearchInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "cia-search": LocalJSX.CiaSearch & JSXBase.HTMLAttributes<HTMLCiaSearchElement>;
            "cia-search-input": LocalJSX.CiaSearchInput & JSXBase.HTMLAttributes<HTMLCiaSearchInputElement>;
        }
    }
}
