/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface CiaDocument {
        "actions": {name: string, isVisible: boolean}[];
        "headerText": string;
    }
    interface CiaDocumentCensorer {
    }
    interface CiaSearch {
        "isProcessable": boolean;
        "searchText": string;
    }
    interface CiaSearchInput {
        "text": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCiaDocumentElement extends Components.CiaDocument, HTMLStencilElement {
    }
    var HTMLCiaDocumentElement: {
        prototype: HTMLCiaDocumentElement;
        new (): HTMLCiaDocumentElement;
    };
    interface HTMLCiaDocumentCensorerElement extends Components.CiaDocumentCensorer, HTMLStencilElement {
    }
    var HTMLCiaDocumentCensorerElement: {
        prototype: HTMLCiaDocumentCensorerElement;
        new (): HTMLCiaDocumentCensorerElement;
    };
    interface HTMLCiaSearchElement extends Components.CiaSearch, HTMLStencilElement {
    }
    var HTMLCiaSearchElement: {
        prototype: HTMLCiaSearchElement;
        new (): HTMLCiaSearchElement;
    };
    interface HTMLCiaSearchInputElement extends Components.CiaSearchInput, HTMLStencilElement {
    }
    var HTMLCiaSearchInputElement: {
        prototype: HTMLCiaSearchInputElement;
        new (): HTMLCiaSearchInputElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "cia-document": HTMLCiaDocumentElement;
        "cia-document-censorer": HTMLCiaDocumentCensorerElement;
        "cia-search": HTMLCiaSearchElement;
        "cia-search-input": HTMLCiaSearchInputElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CiaDocument {
        "actions"?: {name: string, isVisible: boolean}[];
        "headerText"?: string;
        "onDocumentActionClicked"?: (event: CustomEvent<string>) => void;
    }
    interface CiaDocumentCensorer {
    }
    interface CiaSearch {
        "isProcessable"?: boolean;
        "onProcess"?: (event: CustomEvent<null>) => void;
        "onSearchTextChanged"?: (event: CustomEvent<string>) => void;
        "searchText"?: string;
    }
    interface CiaSearchInput {
        "onInputChanged"?: (event: CustomEvent<string>) => void;
        "text"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "cia-document": CiaDocument;
        "cia-document-censorer": CiaDocumentCensorer;
        "cia-search": CiaSearch;
        "cia-search-input": CiaSearchInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "cia-document": LocalJSX.CiaDocument & JSXBase.HTMLAttributes<HTMLCiaDocumentElement>;
            "cia-document-censorer": LocalJSX.CiaDocumentCensorer & JSXBase.HTMLAttributes<HTMLCiaDocumentCensorerElement>;
            "cia-search": LocalJSX.CiaSearch & JSXBase.HTMLAttributes<HTMLCiaSearchElement>;
            "cia-search-input": LocalJSX.CiaSearchInput & JSXBase.HTMLAttributes<HTMLCiaSearchInputElement>;
        }
    }
}
